#!/bin/sh

set -e
umask 0002

OPTIONS="--set name --hostname name --polar disabled --integer-minimum 0 --integer interval --required --relation-base /etc/device/services/db/postgresql/database --relation-name name --relation-suffix .txt --relation database"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart postgresql-backup.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

