#!/bin/sh

set -e
umask 0002

tmpdir="$(mktemp -d)"
trap 'rm -rf -- "${tmpdir}"' EXIT

OPTIONS="--show name --hostname name --show-table name,database,interval --polar disabled --flag X --integer-minimum 0 --integer interval --required --relation-base /etc/device/services/db/postgresql/database --relation-name name --relation-suffix .txt --relation database"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

