#!/bin/sh

set -e
umask 0002

tmpdir="$(mktemp -d)"
trap 'rm -rf -- "${tmpdir}"' EXIT

/usr/bin/locale -a > "${tmpdir}/locales.txt"

OPTIONS="--show name --hostname name --show-table name,locale,database-name,local-owner,instance --select-base "${tmpdir}/locales.txt" --select locale --required --sql-id database-name --user-group postgres --user local-owner --required --relation-base /etc/device/services/db/postgresql/instance --relation-name name --relation-suffix .txt --relation instance"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

