#!/bin/bash

#
# Postgresql Autodiscovery
# ========================
#
# This script autogenerates any required postgresql instances.

set -e
umask 0007

exec 2> >(logger -t ${0})

request="${1}"
instance="${2}"


#
# Handle the cleanup
# ------------------
cleanup_before_exit () {
  if [ -d "${tmpdir}" ]; then
    rm -rf "${tmpdir}"
  fi
}
# be in a temporay workspace (this works on linux and macosx)
tmpdir=`mktemp -d 2>/dev/null || mktemp -d -t 'tmpdir'`
# trap catches the exit signal and runs the specified function
trap cleanup_before_exit EXIT
# be in our directory
cd "${tmpdir}"


#
# Per instance? Run all scripts

if [ $# -ge 2 ]; then

  logger -t "postgresql-autodiscovery" "running autodiscovery for postgresql instance ${instance}..."

  find "$0.d" -type f -executable | sort | \
  while read x; do
    "$x" "${request}" "${instance}" < /dev/null || echo -n "$x" > error;

    if test -f "error"; then
      logger -t "postgresql-autodiscovery" "failed autodiscovery for postgresql instance ${instance} in ${x}."
      exit 1
    fi
  done

  logger -t "postgresql-autodiscovery" "completed autodiscovery for postgresql instance ${instance}."

  exit 0

fi


#
# Add/remove postgres instances

find /etc/device/services/db/postgresql/instance/ -mindepth 1 -maxdepth 1 -type l | \
while read line; do

  if test ! -f "$line/name.txt"; then
    continue;
  fi
  instance="$(head -n 1 $line/name.txt)"

  systemctl --no-block restart "postgresql-autodiscovery@${instance}"

done

