#!/bin/bash
  
#
# Postgresql Postdiscovery
# ========================
#
# This script autogenerates any required postgresql databases.

set -e

request="${1}"

#
# Silence warnings with runuser.
cd /tmp


#
# Add/remove postgresql databases

find /etc/device/services/db/postgresql/database/ -mindepth 1 -maxdepth 1 -type l | \
while read line; do

  if test ! -f "$line/name.txt"; then
    continue;
  fi

  if test ! -f "$line/instance.d/name.txt"; then
    instance=""
  else
    instance="$(head -n 1 $line/instance.d/name.txt)"
  fi
  if test ! -f "$line/instance.d/port.txt"; then
    port="5432"
  else
    port="$(head -n 1 $line/instance.d/port.txt)"
  fi
  if test ! -f "$line/database-name.txt"; then
    database="$(head -n 1 $line/name.txt)"
  else
    database="$(head -n 1 $line/database-name.txt)"
  fi

  # remove old databases
  if test -f "$line/removed"; then

    # remove database, but only if no error was created making the database
    if test -n "${instance}" -a ! -f "$line/error"; then
      runuser -u postgres -- /usr/bin/dropdb --port=${port} "${database}"
    fi

    # remove folder
    target=$(readlink -f "$line")
    rm -f "${target}"/*
    rmdir "${target}"
    rm -f "${line}"
  fi

  # add new databases
  if test -f "$line/added"; then

    if test -f "$line/locale.txt"; then
      locale="$(head $line/locale.txt)"
    else
      locale="POSIX"
    fi

    encoding="UTF-8"

    # add local user if needed
    role="$(head $line/local-owner.txt)"
    echo "DO \$\$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${role}') THEN CREATE ROLE ${role} WITH LOGIN CREATEDB; END IF; END \$\$;" | runuser -u postgres -- /usr/bin/psql --port=${port}  > /dev/null 2>&1

    # database already exist? mark as an error and do nothing
    runuser -u postgres -- /usr/bin/psql --port=${port} -tc "SELECT 1 FROM pg_database WHERE datname = '${name}'" | grep -q 1 && echo "Database already exists" > "$line/error" && rm -f "$line/added" && exit 1

    # add database
    runuser -u postgres -- /usr/bin/createdb --port=${port} --owner="${role}" --locale="${locale}" --encoding="${encoding}" --template=template0 "${database}"

    rm -f "$line/added"
  fi

done

