#!/bin/bash

exec 2> >(logger -t ${0})

if [ $# -eq 2 ]; then

  request="${1}"
  instance="${2}"

  if test -d "/var/lib/pgsql/data-${instance}"; then
    install -m 600 -o postgres -g postgres "${instance}-hba.conf" /var/lib/pgsql/data-${instance}/pg_hba.conf
  fi

fi

