#!/bin/bash
  
#
# Postgresql Postdiscovery
# ========================
#
# This script autogenerates any required postgresql databases.

set -e

request="${1}"

#
# Silence warnings with runuser.
cd /tmp

#
# Handle the cleanup
# ------------------
cleanup_before_exit () {
  if [ -d "${tmpdir}" ]; then
    rm -rf "${tmpdir}"
  fi
}
# be in a temporary workspace (this works on linux and macosx)
tmpdir=`mktemp -d 2>/dev/null || mktemp -d -t 'tmpdir'`
# trap catches the exit signal and runs the specified function
trap cleanup_before_exit EXIT
# be in our directory
cd "${tmpdir}"



#
# Per instance? Run all scripts

logger -t "postgresql-postdiscovery" "running postdiscovery for postgresql servers..."

find "$0.d" -type f -executable | sort | \
while read x; do
  "$x" "${request}" < /dev/null || touch error;
done

if test ! -f "error"; then
  logger -t "postgresql-postdiscovery" "completed postdiscovery for postgresql servers."
  exit 0
else
  logger -t "postgresql-postdiscovery" "failed postdiscovery for postgresql servers."
  exit 1
fi


