#!/bin/sh
  
set -e
umask 0002

tmpdir="$(mktemp -d)"
trap 'rm -rf -- "${tmpdir}"' EXIT

OPTIONS="--add name --hostname name --polar disabled --integer-minimum 0 --integer max-wal-senders --integer-minimum 0 --integer wal-keep-size --integer-minimum 0 --integer max-replication-slots --required --relation-base /etc/device/services/db/postgresql/instance --relation-name name --relation-suffix .txt --relation instance"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart postgresql-autodiscovery.service
  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart postgresql-postdiscovery.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi


