#!/bin/sh

set -e
umask 0002

tmpdir="$(mktemp -d)"
trap 'rm -rf -- "${tmpdir}"' EXIT

/usr/bin/locale -a > "${tmpdir}/locales.txt"

OPTIONS="--add name --sql-id name --port port --polar disabled --required --symlink-base /usr/libexec/device/services/db/postgresql/instance/type --symlink-suffix .txt --symlink type"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart postgresql-autodiscovery.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi


