#!/bin/sh

set -e
umask 0002

OPTIONS="--show name --show-table name,port --sql-id name --port port"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi


