#!/bin/sh -x

set -e
umask 0002

tmpdir="$(mktemp -d)"
trap 'rm -rf -- "${tmpdir}"' EXIT

/usr/bin/locale -a > "${tmpdir}/locales.txt"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set --add name --sql-id name --select-base "${tmpdir}/locales.txt" --select locale "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart postgresql-postdiscovery.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set --add name --sql-id name --select-base "${tmpdir}/locales.txt" --select locale "$@"

fi

